"use client";

import { useEffect, useState } from "react";

export default function AnalyzePage() {
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [fullName, setFullName] = useState("");

  useEffect(() => {
    const path = window.location.pathname;
    const parts = path.split("/").filter(Boolean);
    if (parts.length >= 3) {
      const name = parts[parts.length - 2] + "/" + parts[parts.length - 1];
      setFullName(name);
      fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: name, lang: "en" }),
      })
        .then((r) => r.json())
        .then((d) => { setReport(d); setLoading(false); })
        .catch(() => setLoading(false));
    } else {
      setLoading(false);
    }
  }, []);

  if (loading) {
    return (
      <main style={{ maxWidth: 900, margin: "0 auto", padding: "32px 20px", fontFamily: "system-ui, sans-serif", background: "#fafbfc", color: "#0f0f1a" }}>
        <p style={{ color: "#999", textAlign: "center", paddingTop: 80 }}>Analyzing {fullName || "..."}</p>
      </main>
    );
  }

  if (!report || !report.openscoutScore) {
    return (
      <main style={{ maxWidth: 900, margin: "0 auto", padding: "32px 20px", fontFamily: "system-ui, sans-serif" }}>
        <h1 style={{ fontSize: 24, fontWeight: 700 }}>GitWorth — {fullName}</h1>
        <p style={{ color: "#6b7280", marginTop: 12 }}>Analysis unavailable. Please try again.</p>
      </main>
    );
  }

  const score = report.openscoutScore || 0;
  return (
    <main style={{ maxWidth: 900, margin: "0 auto", padding: "32px 20px", fontFamily: "system-ui, sans-serif", background: "#fafbfc", color: "#0f0f1a" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 12, margin: "24px 0 8px" }}>
        <span style={{ fontSize: 40, fontWeight: 700 }}>{score}</span>
        <span style={{ color: "#999", fontSize: 18 }}>/ 100</span>
      </div>
      <h2 style={{ fontSize: 24, fontWeight: 700 }}>{fullName}</h2>
      <p style={{ fontSize: 12, color: "#999", marginTop: 20 }}>
        Generated by <a href="https://gitworth-landing.vercel.app/" style={{ color: "#7c3aed" }}>GitWorth</a>
      </p>
    </main>
  );
}
