import type { Metadata } from "next";
import { fetchRepoData } from "@/lib/github";
import { callLLM } from "@/lib/llm";
import { crawlOfficialSite } from "@/lib/crawl";
import { calculateScore } from "@/lib/scorer";

type Props = { params: Promise<{ owner: string; repo: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { owner, repo } = await params;
  const fullName = owner + "/" + repo;
  let desc = "Complete commercial evaluation of " + fullName + ".";
  try {
    const data = await fetchRepoData(fullName);
    if (data.repoInfo.description) desc = data.repoInfo.description.slice(0, 200);
  } catch {}
  return {
    title: "GitWorth Analysis: " + fullName + " — Free GitHub Repo Analyzer",
    description: desc,
    openGraph: { title: "GitWorth — " + fullName + " Commercial Evaluation", description: desc.slice(0, 150), type: "article" },
  };
}

export default async function Page({ params }: Props) {
  const { owner, repo } = await params;
  const fullName = owner + "/" + repo;
  let score = 0;
  let verdict = "";
  let desc = "";
  let lang = "";

  try {
    const data = await fetchRepoData(fullName);
    desc = data.repoInfo.description || "";
    lang = data.repoInfo.language || "";
    const crawl = await crawlOfficialSite(data.repoInfo.homepage);
    const llmInput = {
      fullName: data.repoInfo.fullName, description: data.repoInfo.description, stars: data.repoInfo.stars,
      readmeExcerpt: data.readmeExcerpt.slice(0, 1000), category: "Developer Tool", techStack: [],
      hasPricingPage: crawl.hasPricingPage, hasEnterprisePage: crawl.hasEnterprisePage,
      engineeringHealth: "good", releaseCount: data.releaseCount,
      contributorsCount: data.contributorCount, commits30d: data.commits30d,
    };
    const llm = await callLLM(llmInput, "en");
    const scoring = calculateScore(data, crawl, llm);
    score = scoring.final;
    verdict = llm?.oneLineVerdict || "";
  } catch {}

  return (
    <main style={{ maxWidth: 900, margin: "0 auto", padding: "32px 20px", fontFamily: "system-ui, sans-serif", background: "#fafbfc", color: "#0f0f1a" }}>
      <a href="https://gitworth-landing.vercel.app/" style={{ color: "#7c3aed", textDecoration: "none", fontSize: 14 }}>← GitWorth</a>
      <div style={{ display: "flex", alignItems: "center", gap: 12, margin: "24px 0 8px" }}>
        <span style={{ fontSize: 40, fontWeight: 700 }}>{score > 0 ? score : "—"}</span>
        <span style={{ color: "#999", fontSize: 18 }}>/ 100</span>
      </div>
      {verdict && <p style={{ fontSize: 15, color: "#6b7280", fontStyle: "italic" }}>"{verdict}"</p>}
      <h2 style={{ fontSize: 24, fontWeight: 700, marginTop: 16 }}>{fullName}</h2>
      {desc && <p style={{ color: "#6b7280", marginTop: 8 }}>{desc}</p>}
      {lang && <p style={{ color: "#999", fontSize: 13, marginTop: 6 }}>Language: {lang}</p>}
      <p style={{ fontSize: 12, color: "#999", borderTop: "1px solid #e5e7eb", paddingTop: 16, marginTop: 24 }}>
        Generated by <a href="https://gitworth-landing.vercel.app/" style={{ color: "#7c3aed" }}>GitWorth</a> — Evaluate Before You Build
      </p>
    </main>
  );
}
